name: MacOS Build & Test

on:
  push:
    branches: [ void ]
  pull_request:
    branches: [ void ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Selecting Xcode 12.2
      run: sudo xcode-select --switch /Applications/Xcode_12.2.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
